### ISSUE TITLE
阅读《统计学习方法》

### ISSUE THREAD

**Issue by jetxa** [jetxa/jetxa.github.io#1]
:boom:开始阅读李航博士的《统计学习方法》

**Comment by zhxt0** [comment]
# 第二章 感知机
二分类的线性分类模型，判别模型
## 2.1 感知机模型
![gif](https://user-images.githubusercontent.com/7609775/40523003-373dbba2-6006-11e8-97ac-17e563318e84.gif)
平面的法向量w
## 2.2 学习策略
损失为误分类点到超平面的距离：
![codecogseqn](https://user-images.githubusercontent.com/7609775/40522968-ffa37e34-6005-11e8-9c33-28c82b3771aa.gif)
## 2.3 学习算法
### 原始形式
梯度下降
证明收敛性
### 对偶形式
讲w和b表示为实例x和标记y的线性组合，通过求解线性组合的系数来解w和b
![codecogseqn 1](https://user-images.githubusercontent.com/7609775/40523154-edab29e2-6006-11e8-80a1-8256e664bfe6.gif)

**Comment by zhxt0** [comment]
# 第三章 k近邻
基本的分类与回归方法
## 3.1 k近邻算法
k=1：最近邻
## 3.2 k近邻模型
### 距离度量
L_p距离等
### k值的选择
k值小，模型复杂，容易过拟合
**k一般取一个较小的数值，通常采用交叉验证法来选取最优的k值**
### 分类决策规则
如多数表决
## 3.3 kd树
构造、搜索

**Comment by zhxt0** [comment]
# 第四章 朴素贝叶斯
典型的生成学习方法
学习输入输出的联合概率分布
## 4.1 基于朴素贝叶斯的学习与分类
基本假设是条件独立性，即用于分类的特征在类确定的条件下都是条件独立的

## 4.2 朴素贝叶斯的参数估计
### 极大似然估计
### 贝叶斯估计
用极大似然可能会出现所要估计的概率值为0的情况，这时会影响到后验概率的计算，使分类产生误差，在各个取值的频数上添加一个正数 lambda > 0，常取lambda=1，这时称为拉普拉斯平滑

**Comment by zhxt0** [comment]
还剩条件随机场
