### ISSUE TITLE
ssh转发X11

### ISSUE THREAD

**Issue by jetxa** [jetxa/jetxa.github.io#19]
# 服务器端
+ sshd_config中X11取消注释并yes

# 本机
+ 本机ssh时-X
+ 确保xauth安装, 可能要注意.Xauthority的权限?
+ ssh后输入,服务器端输入xclock是否本地显示

# 关于DISPLAY变量
+ 不需要特别设置

# python调试程序
测试本地能否显示matplotlib
```
import matplotlib
matplotlib.use('tkagg')
import matplotlib.pyplot as plt
plt.plot([1, 2, 3])
plt.show()
```

**Comment by zhxt0** [comment]
好像是一导入matplotlib就要use(tkagg)
