### ISSUE TITLE
LaTeX 相关

### ISSUE THREAD

**Issue by jetxa** [jetxa/jetxa.github.io#22]

**Comment by zhxt0** [comment]
页眉页脚相关设置

https://texblog.org/2007/11/07/headerfooter-in-latex-with-fancyhdr/

**Comment by zhxt0** [comment]
titlesec相关

https://blog.csdn.net/dahaiyudong/article/details/79405438

**Comment by zhxt0** [comment]
`xeCJK`

For Chinese, the command \setCJKmainfont{} are used to set up the font used by main text, which is also used by \textrm{} command. \setCJKmonofont{} is used to set up the font used by \texttt{}. \setCJKsansfont{} is used to set up the font used by \textsf{}.
